chore: update domains page title
nsdonato/recursostech pull request #2
Opened 2024-01-26 18:59 UTC by guguponce

El titulo de la pagina de dominios era Fuentes, cambiado ahora a Dominios

# RecursosTech PR Template

## Descripcion ✏️

## Cambios visuales 🎨

## Como testear? 🐛

<!-- Noe @vamoacodear>

2024-01-26 19:05 UTC, nsdonato commented
Muchas gracias por el aporte ♥️

2024-01-26 19:05 UTC, nsdonato approved these changes

2024-01-26 19:09 UTC, nsdonato commented on docs/frontend/domains.mdx
>  contributors:
Cuando solucione un bug que acabo de encontrar, te agrego a esta pagina en contributors, gracias!

2024-01-26 19:16 UTC, nsdonato requested changes

2024-01-26 19:16 UTC, nsdonato commented on docs/frontend/domains.mdx
>  contributors:
Tengo que meter un fix visual, pero te podes sumar como contribuidor, de esta manera:

```suggestion
contributors:
  - github_username: 'nsdonato'
  - github_username: 'guguponce'
```

2024-01-26 21:30 UTC, guguponce commented on docs/frontend/domains.mdx
>  contributors:
Me siento un poco chanta sumandome como contribuidor por esto! Muchas gracias igual por la oferta!
Voy a buscar como mas aportar y en ese caso te acepto la oferta 😁

2024-01-26 21:46 UTC, nsdonato commented on docs/frontend/domains.mdx
>  contributors:
Si no te agregas vos, te agrego yo, todo aporte es un aporte! he dicho.

2024-01-27 11:47 UTC, nsdonato approved these changes

2024-01-27 19:20 UTC, nsdonato approved these changes

2024-01-27 19:21 UTC, merged