feat(vscode):add Easy Snippets
nsdonato/recursostech pull request #4
Opened 2024-01-26 19:21 UTC by Victorioo

# RecursosTech PR Template

## Descripcion ✏️

Se agrega Easy Snippets en el apartado de vscode, una extension para poder crear facilmente snippets, con la palabra que queramos

## Cambios visuales 🎨
## Como testear? 🐛

2024-01-26 19:26 UTC, nsdonato requested changes

2024-01-26 19:26 UTC, nsdonato commented on docs/vscode/extensions.mdx
>    - github_username: 'nsdonato'
Agregá acá tu usuario! Gracias por el aporte <3 

```suggestion
  - github_username: 'nsdonato'
  - github_username: 'Victorioo'
```

2024-01-26 19:41 UTC, Victorioo reviewed
añadido mi github username

2024-01-26 19:49 UTC, nsdonato approved these changes

2024-01-26 19:55 UTC, nsdonato requested changes

2024-01-26 19:55 UTC, nsdonato commented on docs/vscode/extensions.mdx
> +    createdAt: '2024-01-14T00:00:00Z'
Perdón, me olvidé que faltaría actualizar la fecha en ambas propiedades, ya que es un recurso nuevo, de esta manera aparecera el flag en la card!

```suggestion
    createdAt: '2024-01-26T00:00:00Z'
    updatedAt: '2024-01-26T00:00:00Z'
```

Ya veré próximamente como hacer que esto se haga automáticamente, muchas gracias!

2024-01-26 20:04 UTC, Victorioo commented on docs/vscode/extensions.mdx
> +    createdAt: '2024-01-14T00:00:00Z'
No hay drama, abro otra PR editando todo?

2024-01-26 20:38 UTC, nsdonato commented on docs/vscode/extensions.mdx
> +    createdAt: '2024-01-14T00:00:00Z'
Hacelo en esta misma, que está todo relacionado, gracias!

2024-01-27 11:53 UTC, nsdonato requested changes

2024-01-27 11:53 UTC, nsdonato commented on docs/menu.mdx
> +      createdAt: '2024-01-26T00:00:00Z'
La actualización de la fecha era sobre **updatedAt**, pero como se mergeó algo antes que actualizó esa sección podes volver este cambio atras y ya estaría, gracias!

2024-01-29 04:14 UTC, Victorioo reviewed
✅ Cambiada la fecha de **createdAt**

2024-01-29 08:54 UTC, nsdonato commented on docs/menu.mdx
> +      createdAt: '2024-01-26T00:00:00Z'
Veo que se actualizó createdAt en el menu, pero era updatedAt. El menu se creó el 14, pero era necesario marcarlo como que se actualizó el 26 por este nuevo item que se agregó.

Este cambio de fecha es para que la gente sepa que hubo una actualización dentro del menú.

Podrás corregirlo porfi? Gracias!

2024-01-29 23:47 UTC, Victorioo reviewed
✅

2024-01-30 18:37 UTC, nsdonato approved these changes

2024-01-30 18:39 UTC, merged