feat(icons): Update SVG's covers
nsdonato/recursostech pull request #50
Opened 2024-01-31 15:26 UTC by isahernz

## Descripcion ✏️
Se ha realizado la actualización de los covers de las librerías de iconos, agregando los logos de cada librería y actualizando los sources de las mismas. Se ha respetado el tamaño asignado para icono.

## Cambios visuales 🎨
Antes:
![image](https://github.com/nsdonato/recursostech/assets/156483190/b93b97de-58e3-4151-9fac-2551042fc996)

Después:
![image](https://github.com/nsdonato/recursostech/assets/156483190/8b958c3a-eb5a-4b67-b455-930821611f3a)

## Como testear? 🐛

> [!IMPORTANT]
> Checklist a modo recordatorio. Tildar lo que corresponda

- [x] Te agregaste como contribuidor/a, en el archivo mdx que tocaste?
- [ ] Si tocaste código (no mdx), agregaste test para cubrirlo?

2024-01-31 19:42 UTC, nsdonato requested changes
Se dejaron unos comentarios, el resto está todo excelente, muchas gracias por el aporte!

2024-01-31 19:42 UTC, nsdonato commented on public/frontend/animatedicons.svg
> +<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
Este se ve mal en modo oscuro, no se si es posible que el fondo sea transparente 

![image](https://github.com/nsdonato/recursostech/assets/7875216/5c57230e-f626-450e-9a9b-f6268b1ab0c8)

2024-01-31 19:42 UTC, nsdonato commented on docs/frontend/icons.mdx
> +    updatedAt: '2024-01-31T00:00:00Z'
Tendrias que traerte los cambios de main, se eliminó todo esto de createdAt y demás que finalmente no vamos a usar, gracias!

2024-01-31 20:37 UTC, isahernz commented on public/frontend/animatedicons.svg
> +<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
Establecí el fill del icono a none de tal manera que dependiendo del modo que se tenga habilitado no se establezca.
Modo claro:
![image](https://github.com/nsdonato/recursostech/assets/156483190/4f251fa8-7fe6-4fe1-b0cd-c37622b03e72)

Modo oscuro:
![image](https://github.com/nsdonato/recursostech/assets/156483190/4b28e25d-b651-4e8c-bd94-4c8d56934228)

2024-01-31 20:39 UTC, isahernz commented on docs/frontend/icons.mdx
> +    updatedAt: '2024-01-31T00:00:00Z'
¡Listo! Me he traído los últimos cambios de main a la rama de la PR, ajustando los cambios del ancho de los covers de las librerías de iconos.

2024-01-31 20:40 UTC, isahernz commented
¡Listo! He corregido los detalles :D

2024-02-04 20:58 UTC, nsdonato approved these changes

2024-02-04 20:58 UTC, nsdonato commented
Muchas gracias!

2024-02-04 20:58 UTC, merged