feat: update domains and conferences of colombia
nsdonato/recursostech pull request #62
Opened 2024-02-02 00:58 UTC by ArgeNH

## Descripcion ✏️

## Cambios visuales 🎨

## Como testear? 🐛

> [!IMPORTANT]
> Checklist a modo recordatorio. Tildar lo que corresponda

- [ ] Te agregaste como contribuidor/a, en el archivo mdx que tocaste?
- [ ] Si tocaste código (no mdx), agregaste test para cubrirlo?

2024-02-04 20:50 UTC, nsdonato requested changes

2024-02-04 20:50 UTC, nsdonato commented on docs/frontend/domains.mdx
>  ---
Te faltaría agregarte como contributor en este archivo

2024-02-05 00:00 UTC, ArgeNH commented
fixed! 😰

2024-02-05 20:36 UTC, nsdonato approved these changes

2024-02-05 20:36 UTC, merged

2024-02-05 20:38 UTC, nsdonato commented
Listo, gracias!!