adding-frontend-colors
nsdonato/recursostech pull request #77
Opened 2024-02-08 02:03 UTC by mariaelisaaraya

## Descripcion ✏️
Se agrega información en la sección Frontend-Colors.

## Cambios visuales 🎨
![recursos-tech](https://github.com/nsdonato/recursostech/assets/42949801/f84df64d-ed72-4081-8b56-71393e0dd0eb)

- [X] ¿Te agregaste como contribuidor/a, en el archivo mdx que tocaste?
- [X] - Agregué un link y funciona correctamente.
- [ ] Si tocaste código (no mdx) ¿Agregaste test para cubrirlo?

2024-02-08 08:02 UTC, nsdonato requested changes

2024-02-08 08:02 UTC, nsdonato commented on docs/frontend/colors_palette.mdx
> +      width: 190
Podrás probar de bajar un poco el widht tanto de esta como la otra para que quede mejor el svg,? Acá se nota que uno se corta (coolcontrast) y el otro queda muy grande:

![image](https://github.com/nsdonato/recursostech/assets/7875216/5c63f4e7-4115-4c51-ad66-ae5fa1c6cd86)

Gracias por el aporte!

2024-02-10 15:13 UTC, mariaelisaaraya commented on docs/frontend/colors_palette.mdx
> +      width: 190
Realizado:
![2024-02-10_12-05](https://github.com/nsdonato/recursostech/assets/42949801/cf24da86-0f7b-442a-b244-d5cb0c930011)

2024-02-10 18:12 UTC, nsdonato approved these changes

2024-02-10 18:13 UTC, merged

2024-02-10 18:13 UTC, nsdonato commented on docs/frontend/colors_palette.mdx
> +      width: 190
Excelente, gracias!