feat: frontend/colors add resource coolors
nsdonato/recursostech pull request #78
Opened 2024-02-08 11:17 UTC by mig-code

## Descripcion ✏️

Añadir recurso Coolors a seccion Front End Colores

## Cambios visuales 🎨

![rec-tec-after](https://github.com/nsdonato/recursostech/assets/99726342/1682d51c-c11f-48e6-b4bd-569537435e41)

## Como testear? 🐛

> [!IMPORTANT]
> Checklist a modo recordatorio. Tildar lo que corresponda

- [ x] Te agregaste como contribuidor/a, en el archivo mdx que tocaste?
- [ ] Si tocaste código (no mdx), agregaste test para cubrirlo?

2024-02-13 19:40 UTC, nsdonato requested changes

2024-02-13 19:40 UTC, nsdonato commented on docs/frontend/colors_palette.mdx
> +      src: '/frontend/coolors.svg'
podrías cambiar el nombre al svg? a coolors.no-invert.svg mismo al propio archivo, esto hace que mantenga el color tanto en light como en dark mode, muchas gracias!

2024-02-14 10:38 UTC, mig-code commented on docs/frontend/colors_palette.mdx
> +      src: '/frontend/coolors.svg'
Perfecto, mucho mejor así.

2024-03-02 18:07 UTC, merged

2024-03-02 18:13 UTC, nsdonato commented
Gracias por el aporte!